- name: Frontend Setup
  hosts: all
  become: yes
  tasks:
    - name: Install the latest version of Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name:  Start Nginx
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx