- name: Mysql Setup
  hosts: all
  become: yes
  tasks:
    - name: Install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: start mysql service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes
#    - name: install Python-Mysql
#      ansible.builtin.pip:
#        name:
#          - PyMySQL
#          - cryptography
#        executable: pip3.9
    - name: Setup mysql password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
#    - name: Setup mysql password
#      community.mysql.mysql_db:
#        check_implicit_admin: true
#        login_user: root
#        login_password: ExpenseApp@1
#        login_host: mysql-dev.ramdevops78.online
#        name: mysqld
#        state: present


 # mysql_secure_installation --set-root-pass ExpenseApp@1

#  mysql -h mysql-dev.ramdevops78.online -uroot -pExpenseApp@1





