format_version: 10
pipelines:
  mysql:
    group: defaultGroup
    #    label_template: ${COUNT}
    #    lock_behavior: none
    #    display_order: -1
    materials:
      git-f14e4aa:
        git: https://github.com/chinnak7416/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          #         keep_artifacts: false
          #         clean_workspace: false
          approval:
            type: manual
          #           allow_only_on_success: false
          jobs:
            ansible-playbook:
              #             timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                    command: bash # bash ansible.sh mysql
                    run_if: passed

      - QA:
          fetch_materials: true
          environment_variables:
            env: qa
          #         keep_artifacts: false
          #         clean_workspace: false
          approval:
            type: manual
          #           allow_only_on_success: false
          jobs:
            ansible-playbook:
              #             timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                    command: bash # bash ansible.sh mysql
                    run_if: passed

      - STAGE:
          fetch_materials: true
          environment_variables:
            env: stage
          #         keep_artifacts: false
          #         clean_workspace: false
          approval:
            type: manual
          #           allow_only_on_success: false
          jobs:
            ansible-playbook:
              #             timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                    command: bash # bash ansible.sh mysql
                    run_if: passed

      - PROD:
          fetch_materials: true
          environment_variables:
            env: prod
          #         keep_artifacts: false
          #         clean_workspace: false
          approval:
            type: manual
          #           allow_only_on_success: false
          jobs:
            ansible-playbook:
              #             timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                    command: bash # bash ansible.sh mysql
                    run_if: passed