- name: Install Nginx Module for NewRelic
  ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY={{NEW_RELIC_KEY}} NEW_RELIC_ACCOUNT_ID=4410124 /usr/local/bin/newrelic install -y
